// Code generated by BobGen mysql v0.50.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var Labels = Table[
	labelColumns,
	labelIndexes,
	labelForeignKeys,
	labelUniques,
	labelChecks,
]{
	Schema: "",
	Name:   "labels",
	Columns: labelColumns{
		ID: column{
			Name:      "id",
			DBType:    "bigint unsigned",
			Default:   "AUTO_INCREMENT",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  true,
		},
		Name: column{
			Name:      "name",
			DBType:    "varchar(255)",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "datetime",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "datetime",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: labelIndexes{
		IndexLabelsOnName: index{
			Type: "BTREE",
			Name: "index_labels_on_name",
			Columns: []indexColumn{
				{
					Name:         "name",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
		},
		PRIMARY: index{
			Type: "BTREE",
			Name: "PRIMARY",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
		},
	},
	PrimaryKey: &constraint{
		Name:    "PRIMARY",
		Columns: []string{"id"},
		Comment: "",
	},

	Uniques: labelUniques{
		IndexLabelsOnName: constraint{
			Name:    "index_labels_on_name",
			Columns: []string{"name"},
			Comment: "",
		},
	},

	Comment: "",
}

type labelColumns struct {
	ID        column
	Name      column
	CreatedAt column
	UpdatedAt column
}

func (c labelColumns) AsSlice() []column {
	return []column{
		c.ID, c.Name, c.CreatedAt, c.UpdatedAt,
	}
}

type labelIndexes struct {
	IndexLabelsOnName index
	PRIMARY           index
}

func (i labelIndexes) AsSlice() []index {
	return []index{
		i.IndexLabelsOnName, i.PRIMARY,
	}
}

type labelForeignKeys struct{}

func (f labelForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type labelUniques struct {
	IndexLabelsOnName constraint
}

func (u labelUniques) AsSlice() []constraint {
	return []constraint{
		u.IndexLabelsOnName,
	}
}

type labelChecks struct{}

func (c labelChecks) AsSlice() []check {
	return []check{}
}
