// Code generated by BobGen mysql v0.50.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var Tasks = Table[
	taskColumns,
	taskIndexes,
	taskForeignKeys,
	taskUniques,
	taskChecks,
]{
	Schema: "",
	Name:   "tasks",
	Columns: taskColumns{
		ID: column{
			Name:      "id",
			DBType:    "bigint unsigned",
			Default:   "AUTO_INCREMENT",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  true,
		},
		Name: column{
			Name:      "name",
			DBType:    "varchar(20)",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Description: column{
			Name:      "description",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		Status: column{
			Name:      "status",
			DBType:    "tinyint unsigned",
			Default:   "1",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		FinishedOn: column{
			Name:      "finished_on",
			DBType:    "date",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UserID: column{
			Name:      "user_id",
			DBType:    "bigint unsigned",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "datetime",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "datetime",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: taskIndexes{
		IndexTasksOnFinishedOn: index{
			Type: "BTREE",
			Name: "index_tasks_on_finished_on",
			Columns: []indexColumn{
				{
					Name:         "finished_on",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  false,
			Comment: "",
		},
		IndexTasksOnStatus: index{
			Type: "BTREE",
			Name: "index_tasks_on_status",
			Columns: []indexColumn{
				{
					Name:         "status",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  false,
			Comment: "",
		},
		IndexTasksOnUserID: index{
			Type: "BTREE",
			Name: "index_tasks_on_user_id",
			Columns: []indexColumn{
				{
					Name:         "user_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  false,
			Comment: "",
		},
		PRIMARY: index{
			Type: "BTREE",
			Name: "PRIMARY",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
		},
	},
	PrimaryKey: &constraint{
		Name:    "PRIMARY",
		Columns: []string{"id"},
		Comment: "",
	},

	Comment: "",
}

type taskColumns struct {
	ID          column
	Name        column
	Description column
	Status      column
	FinishedOn  column
	UserID      column
	CreatedAt   column
	UpdatedAt   column
}

func (c taskColumns) AsSlice() []column {
	return []column{
		c.ID, c.Name, c.Description, c.Status, c.FinishedOn, c.UserID, c.CreatedAt, c.UpdatedAt,
	}
}

type taskIndexes struct {
	IndexTasksOnFinishedOn index
	IndexTasksOnStatus     index
	IndexTasksOnUserID     index
	PRIMARY                index
}

func (i taskIndexes) AsSlice() []index {
	return []index{
		i.IndexTasksOnFinishedOn, i.IndexTasksOnStatus, i.IndexTasksOnUserID, i.PRIMARY,
	}
}

type taskForeignKeys struct{}

func (f taskForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type taskUniques struct{}

func (u taskUniques) AsSlice() []constraint {
	return []constraint{}
}

type taskChecks struct{}

func (c taskChecks) AsSlice() []check {
	return []check{}
}
