// Code generated by BobGen mysql v0.50.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var TaskLabels = Table[
	taskLabelColumns,
	taskLabelIndexes,
	taskLabelForeignKeys,
	taskLabelUniques,
	taskLabelChecks,
]{
	Schema: "",
	Name:   "task_labels",
	Columns: taskLabelColumns{
		ID: column{
			Name:      "id",
			DBType:    "bigint unsigned",
			Default:   "AUTO_INCREMENT",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  true,
		},
		TaskID: column{
			Name:      "task_id",
			DBType:    "bigint unsigned",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		LabelID: column{
			Name:      "label_id",
			DBType:    "bigint unsigned",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "datetime",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "datetime",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: taskLabelIndexes{
		IndexTaskLabelOnUniqKey: index{
			Type: "BTREE",
			Name: "index_task_label_on_uniq_key",
			Columns: []indexColumn{
				{
					Name:         "task_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
				{
					Name:         "label_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
		},
		IndexTaskLabelsOnLabelID: index{
			Type: "BTREE",
			Name: "index_task_labels_on_label_id",
			Columns: []indexColumn{
				{
					Name:         "label_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  false,
			Comment: "",
		},
		PRIMARY: index{
			Type: "BTREE",
			Name: "PRIMARY",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
		},
	},
	PrimaryKey: &constraint{
		Name:    "PRIMARY",
		Columns: []string{"id"},
		Comment: "",
	},

	Uniques: taskLabelUniques{
		IndexTaskLabelOnUniqKey: constraint{
			Name:    "index_task_label_on_uniq_key",
			Columns: []string{"task_id", "label_id"},
			Comment: "",
		},
	},

	Comment: "",
}

type taskLabelColumns struct {
	ID        column
	TaskID    column
	LabelID   column
	CreatedAt column
	UpdatedAt column
}

func (c taskLabelColumns) AsSlice() []column {
	return []column{
		c.ID, c.TaskID, c.LabelID, c.CreatedAt, c.UpdatedAt,
	}
}

type taskLabelIndexes struct {
	IndexTaskLabelOnUniqKey  index
	IndexTaskLabelsOnLabelID index
	PRIMARY                  index
}

func (i taskLabelIndexes) AsSlice() []index {
	return []index{
		i.IndexTaskLabelOnUniqKey, i.IndexTaskLabelsOnLabelID, i.PRIMARY,
	}
}

type taskLabelForeignKeys struct{}

func (f taskLabelForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type taskLabelUniques struct {
	IndexTaskLabelOnUniqKey constraint
}

func (u taskLabelUniques) AsSlice() []constraint {
	return []constraint{
		u.IndexTaskLabelOnUniqKey,
	}
}

type taskLabelChecks struct{}

func (c taskLabelChecks) AsSlice() []check {
	return []check{}
}
