// Code generated by BobGen mysql v0.50.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"github.com/stephenafamo/bob/clause"
	"github.com/stephenafamo/bob/dialect/mysql"
	"github.com/stephenafamo/bob/dialect/mysql/dialect"
)

var (
	SelectWhere     = Where[*dialect.SelectQuery]()
	UpdateWhere     = Where[*dialect.UpdateQuery]()
	DeleteWhere     = Where[*dialect.DeleteQuery]()
	OnConflictWhere = Where[*clause.ConflictClause]() // Used in ON CONFLICT DO UPDATE
)

func Where[Q mysql.Filterable]() struct {
	Labels     labelWhere[Q]
	TaskLabels taskLabelWhere[Q]
	Tasks      taskWhere[Q]
} {
	return struct {
		Labels     labelWhere[Q]
		TaskLabels taskLabelWhere[Q]
		Tasks      taskWhere[Q]
	}{
		Labels:     buildLabelWhere[Q](Labels.Columns),
		TaskLabels: buildTaskLabelWhere[Q](TaskLabels.Columns),
		Tasks:      buildTaskWhere[Q](Tasks.Columns),
	}
}
