// Code generated by BobGen mysql v0.50.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"database/sql"
	"database/sql/driver"

	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/types"
)

// Set the testDB to enable tests that use the database
var testDB bob.Transactor[bob.Tx]

// Make sure the type Label runs hooks after queries
var _ bob.HookableType = &Label{}

// Make sure the type TaskLabel runs hooks after queries
var _ bob.HookableType = &TaskLabel{}

// Make sure the type Task runs hooks after queries
var _ bob.HookableType = &Task{}

// Make sure the type types.Uint64 satisfies database/sql.Scanner
var _ sql.Scanner = (*types.Uint64)(nil)

// Make sure the type types.Uint64 satisfies database/sql/driver.Valuer
var _ driver.Valuer = *new(types.Uint64)
