// Code generated by BobGen mysql v0.50.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"io"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/mysql"
	"github.com/stephenafamo/bob/dialect/mysql/dialect"
	"github.com/stephenafamo/bob/dialect/mysql/dm"
	"github.com/stephenafamo/bob/dialect/mysql/sm"
	"github.com/stephenafamo/bob/dialect/mysql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/types"
	"github.com/stephenafamo/scan"
)

// Label is an object representing the database table.
type Label struct {
	ID        types.Uint64 `db:"id,pk,autoincr" `
	Name      string       `db:"name" `
	CreatedAt time.Time    `db:"created_at" `
	UpdatedAt time.Time    `db:"updated_at" `
}

// LabelSlice is an alias for a slice of pointers to Label.
// This should almost always be used instead of []*Label.
type LabelSlice []*Label

// Labels contains methods to work with the labels table
var Labels = mysql.NewTablex[*Label, LabelSlice, *LabelSetter]("labels", buildLabelColumns("labels"), labelScanMapper, []string{"id"}, []string{"name"})

// LabelsQuery is a query on the labels table
type LabelsQuery = *mysql.ViewQuery[*Label, LabelSlice]

func buildLabelColumns(tableName string) labelColumns {
	columnsExpr := expr.NewColumnsExpr(
		"id", "name", "created_at", "updated_at",
	)

	if tableName != "" {
		columnsExpr = columnsExpr.WithParent(tableName)
	}

	return labelColumns{
		ColumnsExpr: columnsExpr,
		tableAlias:  tableName,
		ID:          buildLabelColumn(tableName, "id"),
		Name:        buildLabelColumn(tableName, "name"),
		CreatedAt:   buildLabelColumn(tableName, "created_at"),
		UpdatedAt:   buildLabelColumn(tableName, "updated_at"),
	}
}

type labelColumns struct {
	expr.ColumnsExpr
	tableAlias string
	ID         labelColumn
	Name       labelColumn
	CreatedAt  labelColumn
	UpdatedAt  labelColumn
}

// Alias returns the current table alias for the columns set.
func (c labelColumns) Alias() string {
	return c.tableAlias
}

// AliasedAs returns a copy of the columns set qualified by tableName.
func (labelColumns) AliasedAs(tableName string) labelColumns {
	return buildLabelColumns(tableName)
}

// Unqualified returns a copy of the columns set without table qualification.
func (c labelColumns) Unqualified() labelColumns {
	return buildLabelColumns("")
}

func buildLabelColumn(alias, name string) labelColumn {
	return labelColumn{
		Expression: mysql.Quote(alias, name),
		alias:      alias,
		name:       name,
	}
}

type labelColumn struct {
	mysql.Expression
	alias string
	name  string
}

// Name returns the unqualified column name.
func (c labelColumn) Name() string {
	return c.name
}

// ShouldOmitParens prevents automatic parenthesis wrapping in expression builders.
func (c labelColumn) ShouldOmitParens() bool {
	return true
}

// LabelSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type LabelSetter struct {
	ID        omit.Val[types.Uint64] `db:"id,pk,autoincr" `
	Name      omit.Val[string]       `db:"name" `
	CreatedAt omit.Val[time.Time]    `db:"created_at" `
	UpdatedAt omit.Val[time.Time]    `db:"updated_at" `
}

func (s LabelSetter) SetColumns() []string {
	vals := make([]string, 0, 4)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.Name.IsValue() {
		vals = append(vals, "name")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s LabelSetter) Overwrite(t *Label) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.Name.IsValue() {
		t.Name = s.Name.MustGet()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
}

func (s *LabelSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Labels.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(
		bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.ID.IsUnset() {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.ID.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.Name.IsUnset() {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.Name.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.CreatedAt.IsUnset() {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.CreatedAt.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.UpdatedAt.IsUnset() {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.UpdatedAt.MustGet()).WriteSQL(ctx, w, d, start)
		}))
}

func (s LabelSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions("labels")...)
}

func (s LabelSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 4)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "id")...),
			mysql.Arg(s.ID),
		}})
	}

	if s.Name.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "name")...),
			mysql.Arg(s.Name),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "created_at")...),
			mysql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "updated_at")...),
			mysql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// scan.Mapper[*T] without reflection: maps columns to fields by index.
func labelScanMapper(ctx context.Context, cols []string) (scan.BeforeFunc, func(any) (*Label, error)) {
	// resolve the column positions once per query, not per row
	type target struct {
		idx int
		dst func(o *Label) any
	}
	targets := make([]target, 0, 4)
	for i, col := range cols {
		switch col {
		case "id":
			targets = append(targets, target{i, func(o *Label) any { return &o.ID }})
		case "name":
			targets = append(targets, target{i, func(o *Label) any { return &o.Name }})
		case "created_at":
			targets = append(targets, target{i, func(o *Label) any { return &o.CreatedAt }})
		case "updated_at":
			targets = append(targets, target{i, func(o *Label) any { return &o.UpdatedAt }})
		}
	}

	return func(row *scan.Row) (any, error) {
			o := new(Label)
			for _, t := range targets {
				row.ScheduleScanByIndex(t.idx, t.dst(o))
			}
			return o, nil
		}, func(v any) (*Label, error) {
			return v.(*Label), nil
		}
}

// FindLabel retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindLabel(ctx context.Context, exec bob.Executor, IDPK types.Uint64, cols ...string) (*Label, error) {
	if len(cols) == 0 {
		return Labels.Query(
			sm.Where(Labels.Columns.ID.EQ(mysql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Labels.Query(
		sm.Where(Labels.Columns.ID.EQ(mysql.Arg(IDPK))),
		sm.Columns(Labels.Columns.Only(cols...)),
	).One(ctx, exec)
}

// LabelExists checks the presence of a single record by primary key
func LabelExists(ctx context.Context, exec bob.Executor, IDPK types.Uint64) (bool, error) {
	return Labels.Query(
		sm.Where(Labels.Columns.ID.EQ(mysql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Label is retrieved from the database
func (o *Label) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Labels.AfterSelectHooks.RunHooks(ctx, exec, LabelSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Labels.AfterInsertHooks.RunHooks(ctx, exec, LabelSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Labels.AfterUpdateHooks.RunHooks(ctx, exec, LabelSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Labels.AfterDeleteHooks.RunHooks(ctx, exec, LabelSlice{o})

	}

	return err
}

// primaryKeyVals returns the primary key values of the Label
func (o *Label) primaryKeyVals() bob.Expression {
	return mysql.Arg(o.ID)
}

func (o *Label) pkEQ() dialect.Expression {
	return mysql.Quote("labels", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Label
func (o *Label) Update(ctx context.Context, exec bob.Executor, s *LabelSetter) error {
	_, err := Labels.Update(s.UpdateMod(), um.Where(o.pkEQ())).Exec(ctx, exec)
	if err != nil {
		return err
	}

	s.Overwrite(o)

	return nil
}

// Delete deletes a single Label record with an executor
func (o *Label) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Labels.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Label using the executor
func (o *Label) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Labels.Query(
		sm.Where(Labels.Columns.ID.EQ(mysql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *o2

	return nil
}

// AfterQueryHook is called after LabelSlice is retrieved from the database
func (o LabelSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Labels.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Labels.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Labels.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Labels.AfterDeleteHooks.RunHooks(ctx, exec, o)

	}

	return err
}

func (o LabelSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return mysql.Raw("NULL")
	}

	return mysql.Quote("labels", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o LabelSlice) copyMatchingRows(from ...*Label) {
	fromByPK := make(map[types.Uint64]*Label, len(from))
	for _, new := range from {
		// keep the first row for each key, like the nested loop did
		if _, ok := fromByPK[new.ID]; !ok {
			fromByPK[new.ID] = new
		}
	}

	for i, old := range o {
		new, ok := fromByPK[old.ID]
		if !ok {
			continue
		}

		o[i] = new
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o LabelSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Labels.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Label:
				o.copyMatchingRows(retrieved)
			case []*Label:
				o.copyMatchingRows(retrieved...)
			case LabelSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Label or a slice of Label
				// then run the AfterUpdateHooks on the slice
				_, err = Labels.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o LabelSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Labels.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Label:
				o.copyMatchingRows(retrieved)
			case []*Label:
				o.copyMatchingRows(retrieved...)
			case LabelSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Label or a slice of Label
				// then run the AfterDeleteHooks on the slice
				_, err = Labels.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o LabelSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals LabelSetter) error {
	_, err := Labels.Update(vals.UpdateMod(), o.UpdateMod()).Exec(ctx, exec)

	for i := range o {
		vals.Overwrite(o[i])
	}

	return err
}

func (o LabelSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Labels.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o LabelSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Labels.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

type labelWhere[Q mysql.Filterable] struct {
	cols      labelColumns
	ID        mysql.WhereMod[Q, types.Uint64]
	Name      mysql.WhereMod[Q, string]
	CreatedAt mysql.WhereMod[Q, time.Time]
	UpdatedAt mysql.WhereMod[Q, time.Time]
}

func (labelWhere[Q]) AliasedAs(alias string) labelWhere[Q] {
	return buildLabelWhere[Q](buildLabelColumns(alias))
}

func buildLabelWhere[Q mysql.Filterable](cols labelColumns) labelWhere[Q] {
	return labelWhere[Q]{
		cols:      cols,
		ID:        mysql.Where[Q, types.Uint64](cols.ID.Expression),
		Name:      mysql.Where[Q, string](cols.Name.Expression),
		CreatedAt: mysql.Where[Q, time.Time](cols.CreatedAt.Expression),
		UpdatedAt: mysql.Where[Q, time.Time](cols.UpdatedAt.Expression),
	}
}
