// Code generated by BobGen mysql v0.50.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"io"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/mysql"
	"github.com/stephenafamo/bob/dialect/mysql/dialect"
	"github.com/stephenafamo/bob/dialect/mysql/dm"
	"github.com/stephenafamo/bob/dialect/mysql/sm"
	"github.com/stephenafamo/bob/dialect/mysql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/types"
	"github.com/stephenafamo/scan"
)

// TaskLabel is an object representing the database table.
type TaskLabel struct {
	ID        types.Uint64 `db:"id,pk,autoincr" `
	TaskID    types.Uint64 `db:"task_id" `
	LabelID   types.Uint64 `db:"label_id" `
	CreatedAt time.Time    `db:"created_at" `
	UpdatedAt time.Time    `db:"updated_at" `
}

// TaskLabelSlice is an alias for a slice of pointers to TaskLabel.
// This should almost always be used instead of []*TaskLabel.
type TaskLabelSlice []*TaskLabel

// TaskLabels contains methods to work with the task_labels table
var TaskLabels = mysql.NewTablex[*TaskLabel, TaskLabelSlice, *TaskLabelSetter]("task_labels", buildTaskLabelColumns("task_labels"), taskLabelScanMapper, []string{"id"}, []string{"task_id", "label_id"})

// TaskLabelsQuery is a query on the task_labels table
type TaskLabelsQuery = *mysql.ViewQuery[*TaskLabel, TaskLabelSlice]

func buildTaskLabelColumns(tableName string) taskLabelColumns {
	columnsExpr := expr.NewColumnsExpr(
		"id", "task_id", "label_id", "created_at", "updated_at",
	)

	if tableName != "" {
		columnsExpr = columnsExpr.WithParent(tableName)
	}

	return taskLabelColumns{
		ColumnsExpr: columnsExpr,
		tableAlias:  tableName,
		ID:          buildTaskLabelColumn(tableName, "id"),
		TaskID:      buildTaskLabelColumn(tableName, "task_id"),
		LabelID:     buildTaskLabelColumn(tableName, "label_id"),
		CreatedAt:   buildTaskLabelColumn(tableName, "created_at"),
		UpdatedAt:   buildTaskLabelColumn(tableName, "updated_at"),
	}
}

type taskLabelColumns struct {
	expr.ColumnsExpr
	tableAlias string
	ID         taskLabelColumn
	TaskID     taskLabelColumn
	LabelID    taskLabelColumn
	CreatedAt  taskLabelColumn
	UpdatedAt  taskLabelColumn
}

// Alias returns the current table alias for the columns set.
func (c taskLabelColumns) Alias() string {
	return c.tableAlias
}

// AliasedAs returns a copy of the columns set qualified by tableName.
func (taskLabelColumns) AliasedAs(tableName string) taskLabelColumns {
	return buildTaskLabelColumns(tableName)
}

// Unqualified returns a copy of the columns set without table qualification.
func (c taskLabelColumns) Unqualified() taskLabelColumns {
	return buildTaskLabelColumns("")
}

func buildTaskLabelColumn(alias, name string) taskLabelColumn {
	return taskLabelColumn{
		Expression: mysql.Quote(alias, name),
		alias:      alias,
		name:       name,
	}
}

type taskLabelColumn struct {
	mysql.Expression
	alias string
	name  string
}

// Name returns the unqualified column name.
func (c taskLabelColumn) Name() string {
	return c.name
}

// ShouldOmitParens prevents automatic parenthesis wrapping in expression builders.
func (c taskLabelColumn) ShouldOmitParens() bool {
	return true
}

// TaskLabelSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type TaskLabelSetter struct {
	ID        omit.Val[types.Uint64] `db:"id,pk,autoincr" `
	TaskID    omit.Val[types.Uint64] `db:"task_id" `
	LabelID   omit.Val[types.Uint64] `db:"label_id" `
	CreatedAt omit.Val[time.Time]    `db:"created_at" `
	UpdatedAt omit.Val[time.Time]    `db:"updated_at" `
}

func (s TaskLabelSetter) SetColumns() []string {
	vals := make([]string, 0, 5)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.TaskID.IsValue() {
		vals = append(vals, "task_id")
	}
	if s.LabelID.IsValue() {
		vals = append(vals, "label_id")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s TaskLabelSetter) Overwrite(t *TaskLabel) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.TaskID.IsValue() {
		t.TaskID = s.TaskID.MustGet()
	}
	if s.LabelID.IsValue() {
		t.LabelID = s.LabelID.MustGet()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
}

func (s *TaskLabelSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return TaskLabels.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(
		bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.ID.IsUnset() {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.ID.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.TaskID.IsUnset() {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.TaskID.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.LabelID.IsUnset() {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.LabelID.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.CreatedAt.IsUnset() {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.CreatedAt.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.UpdatedAt.IsUnset() {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.UpdatedAt.MustGet()).WriteSQL(ctx, w, d, start)
		}))
}

func (s TaskLabelSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions("task_labels")...)
}

func (s TaskLabelSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 5)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "id")...),
			mysql.Arg(s.ID),
		}})
	}

	if s.TaskID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "task_id")...),
			mysql.Arg(s.TaskID),
		}})
	}

	if s.LabelID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "label_id")...),
			mysql.Arg(s.LabelID),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "created_at")...),
			mysql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "updated_at")...),
			mysql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// scan.Mapper[*T] without reflection: maps columns to fields by index.
func taskLabelScanMapper(ctx context.Context, cols []string) (scan.BeforeFunc, func(any) (*TaskLabel, error)) {
	// resolve the column positions once per query, not per row
	type target struct {
		idx int
		dst func(o *TaskLabel) any
	}
	targets := make([]target, 0, 5)
	for i, col := range cols {
		switch col {
		case "id":
			targets = append(targets, target{i, func(o *TaskLabel) any { return &o.ID }})
		case "task_id":
			targets = append(targets, target{i, func(o *TaskLabel) any { return &o.TaskID }})
		case "label_id":
			targets = append(targets, target{i, func(o *TaskLabel) any { return &o.LabelID }})
		case "created_at":
			targets = append(targets, target{i, func(o *TaskLabel) any { return &o.CreatedAt }})
		case "updated_at":
			targets = append(targets, target{i, func(o *TaskLabel) any { return &o.UpdatedAt }})
		}
	}

	return func(row *scan.Row) (any, error) {
			o := new(TaskLabel)
			for _, t := range targets {
				row.ScheduleScanByIndex(t.idx, t.dst(o))
			}
			return o, nil
		}, func(v any) (*TaskLabel, error) {
			return v.(*TaskLabel), nil
		}
}

// FindTaskLabel retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindTaskLabel(ctx context.Context, exec bob.Executor, IDPK types.Uint64, cols ...string) (*TaskLabel, error) {
	if len(cols) == 0 {
		return TaskLabels.Query(
			sm.Where(TaskLabels.Columns.ID.EQ(mysql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return TaskLabels.Query(
		sm.Where(TaskLabels.Columns.ID.EQ(mysql.Arg(IDPK))),
		sm.Columns(TaskLabels.Columns.Only(cols...)),
	).One(ctx, exec)
}

// TaskLabelExists checks the presence of a single record by primary key
func TaskLabelExists(ctx context.Context, exec bob.Executor, IDPK types.Uint64) (bool, error) {
	return TaskLabels.Query(
		sm.Where(TaskLabels.Columns.ID.EQ(mysql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after TaskLabel is retrieved from the database
func (o *TaskLabel) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = TaskLabels.AfterSelectHooks.RunHooks(ctx, exec, TaskLabelSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = TaskLabels.AfterInsertHooks.RunHooks(ctx, exec, TaskLabelSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = TaskLabels.AfterUpdateHooks.RunHooks(ctx, exec, TaskLabelSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = TaskLabels.AfterDeleteHooks.RunHooks(ctx, exec, TaskLabelSlice{o})

	}

	return err
}

// primaryKeyVals returns the primary key values of the TaskLabel
func (o *TaskLabel) primaryKeyVals() bob.Expression {
	return mysql.Arg(o.ID)
}

func (o *TaskLabel) pkEQ() dialect.Expression {
	return mysql.Quote("task_labels", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the TaskLabel
func (o *TaskLabel) Update(ctx context.Context, exec bob.Executor, s *TaskLabelSetter) error {
	_, err := TaskLabels.Update(s.UpdateMod(), um.Where(o.pkEQ())).Exec(ctx, exec)
	if err != nil {
		return err
	}

	s.Overwrite(o)

	return nil
}

// Delete deletes a single TaskLabel record with an executor
func (o *TaskLabel) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := TaskLabels.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the TaskLabel using the executor
func (o *TaskLabel) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := TaskLabels.Query(
		sm.Where(TaskLabels.Columns.ID.EQ(mysql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *o2

	return nil
}

// AfterQueryHook is called after TaskLabelSlice is retrieved from the database
func (o TaskLabelSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = TaskLabels.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = TaskLabels.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = TaskLabels.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = TaskLabels.AfterDeleteHooks.RunHooks(ctx, exec, o)

	}

	return err
}

func (o TaskLabelSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return mysql.Raw("NULL")
	}

	return mysql.Quote("task_labels", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o TaskLabelSlice) copyMatchingRows(from ...*TaskLabel) {
	fromByPK := make(map[types.Uint64]*TaskLabel, len(from))
	for _, new := range from {
		// keep the first row for each key, like the nested loop did
		if _, ok := fromByPK[new.ID]; !ok {
			fromByPK[new.ID] = new
		}
	}

	for i, old := range o {
		new, ok := fromByPK[old.ID]
		if !ok {
			continue
		}

		o[i] = new
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o TaskLabelSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return TaskLabels.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *TaskLabel:
				o.copyMatchingRows(retrieved)
			case []*TaskLabel:
				o.copyMatchingRows(retrieved...)
			case TaskLabelSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a TaskLabel or a slice of TaskLabel
				// then run the AfterUpdateHooks on the slice
				_, err = TaskLabels.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o TaskLabelSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return TaskLabels.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *TaskLabel:
				o.copyMatchingRows(retrieved)
			case []*TaskLabel:
				o.copyMatchingRows(retrieved...)
			case TaskLabelSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a TaskLabel or a slice of TaskLabel
				// then run the AfterDeleteHooks on the slice
				_, err = TaskLabels.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o TaskLabelSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals TaskLabelSetter) error {
	_, err := TaskLabels.Update(vals.UpdateMod(), o.UpdateMod()).Exec(ctx, exec)

	for i := range o {
		vals.Overwrite(o[i])
	}

	return err
}

func (o TaskLabelSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := TaskLabels.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o TaskLabelSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := TaskLabels.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

type taskLabelWhere[Q mysql.Filterable] struct {
	cols      taskLabelColumns
	ID        mysql.WhereMod[Q, types.Uint64]
	TaskID    mysql.WhereMod[Q, types.Uint64]
	LabelID   mysql.WhereMod[Q, types.Uint64]
	CreatedAt mysql.WhereMod[Q, time.Time]
	UpdatedAt mysql.WhereMod[Q, time.Time]
}

func (taskLabelWhere[Q]) AliasedAs(alias string) taskLabelWhere[Q] {
	return buildTaskLabelWhere[Q](buildTaskLabelColumns(alias))
}

func buildTaskLabelWhere[Q mysql.Filterable](cols taskLabelColumns) taskLabelWhere[Q] {
	return taskLabelWhere[Q]{
		cols:      cols,
		ID:        mysql.Where[Q, types.Uint64](cols.ID.Expression),
		TaskID:    mysql.Where[Q, types.Uint64](cols.TaskID.Expression),
		LabelID:   mysql.Where[Q, types.Uint64](cols.LabelID.Expression),
		CreatedAt: mysql.Where[Q, time.Time](cols.CreatedAt.Expression),
		UpdatedAt: mysql.Where[Q, time.Time](cols.UpdatedAt.Expression),
	}
}
